### ISSUE TITLE
Config file not found

### ISSUE THREAD

**Issue by heinerlamprecht** [deejayy/ts-depgraph#2]
I'm testing ts-depgraph, which I installed locally in my project as a dev dependency.

A local depgraph.config file is not found, because it is not searched in the current working directory, but in the dist folder of ts-depgraph.  Putting the file into this directory is not really an option, as it needs to be checked in.

Any solution or hint?

**Comment by deejayy** [comment]
Thanks for reporting! I'll check it out asap.

**Comment by deejayy** [comment]
Fix candidate with [commit 10e1ac](https://github.com/deejayy/ts-depgraph/commit/10e1ac97138b9d44c9f691fcd4f27a58831d21b1) is in place, package published, release v0.6.7 is available through npm. Could you please try it out?

**Comment by heinerlamprecht** [comment]
That was fast, awesome.  Work as expected.  Thanks.
